id: eddcbfbf967341e483a17534585279ed
initial_creation_type: ocr
source_metadata:
  volumes:
    bfaf0a5c28d443069dce61817f074ae8:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: བསྟོད་པ་ལས་འདས་པར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
